.Dd August 1, 2022
.Dt XSCREENSHOT 1
.Sh NAME
.Nm xscreenshot
.Nd screenshot utility for X
.Sh SYNOPSIS
.Nm
.Op Fl hpsv
.Op Fl d Ar DIRECTORY
.Sh DESCRIPTION
The
.Nm
utility lets you take a screenshot and save it as a ppm.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h, -help
show usage
.It Fl p, -print
print the screenshot path to stdout
.It Fl s, -stdout
write the .ppm data to stdout
.It Fl v, -version
display the program version
.It Fl d, -directory
set the directory to save the screenshot
.El
.Sh SEE ALSO
.Xr apint 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xscreenshot/issues
