.TH XSCREENSHOT 1 "August 1, 2022"
.SH NAME
xscreenshot \- simple X11 program that takes a screenshot and saves it as a ppm in the specified directory (if any).
.SH SYNOPSIS
\fBxscreenshot\fP [ -hpsv ] [ -d DIRECTORY ]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
display the program version
.TP
\fB\-s\fR, \fB\-\-stdout\fR
write the .ppm data to stdout
.TP
\fB\-p\fR, \fB\-\-print\fR
print the screenshot path to stdout
.TP
\fB\-d\fR, \fB\-\-directory\fR
set the directory to save the screenshot
.SH EXAMPLE
.TP
\fBtake a screenshot and save it to the screenshot directory\fR
xscreenshot -d "$HOME/.screenshots"
.SH EXIT STATUS
.TP
\fB0\fR
a screenshot has been taken
.TP
\fB1\fR
an error occurred
.SH AUTHOR
Written by alpheratz0.
.SH COPYRIGHT
Copyright \(co 2022 <alpheratz99@protonmail.com>
.br
License GPLv2.0: GNU GPL version 2.0 <https://gnu.org/licenses/old-licenses/gpl-2.0.en.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH BUGS
https://github.com/alpheratz0/xscreenshot/issues
