.Dd August 9, 2022
.Dt XSCREENSHOT 1
.Sh NAME
.Nm xscreenshot
.Nd screenshot utility for X
.Sh SYNOPSIS
.Nm
.Op Fl hpv
.Op Fl d Ar directory
.Sh DESCRIPTION
The
.Nm
utility lets you take a screenshot and save it as a ppm.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl p
print the screenshot path to stdout
.It Fl v
display the program version
.It Fl d
set the directory to save the screenshot
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It take a screenshot and save it under ~/.screenshots
xscreenshot -d ~/.screenshots
.It use apint to draw over a freshly taken screenshot
apint -f -l $(xscreenshot -p -d $(mktemp -d))
.El
.Sh SEE ALSO
.Xr X 7
.Xr ppm 5
.Xr apint 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xscreenshot/issues
